function validateParams(p)
%VALIDATEPARAMS Fail early on inconsistent or unsupported configuration.

positive = {'Ntheta','NthetaRobust','NthetaValidation','rho','E_xy','E_z', ...
    'nu_petg','Tout_nominal','robustN','PopulationSize','MaxGenerations', ...
    'ConstraintTolerance'};
for i = 1:numel(positive)
    name = positive{i};
    assert(isfield(p,name) && isscalar(p.(name)) && isfinite(p.(name)) && p.(name)>0, ...
        'CycloidalDrive:InvalidParameter', ...
        'Parameter %s must be positive and finite.',name);
end
assert(any(strcmpi(p.buildPlane,{'XY','Z'})), ...
    'CycloidalDrive:InvalidBuildPlane','buildPlane must be ''XY'' or ''Z''.');
assert(p.nu_petg>0 && p.nu_petg<0.5, ...
    'CycloidalDrive:InvalidPoissonRatio','nu_petg must be between 0 and 0.5.');
assert(p.shortWidthCoefficientMin>0 && ...
       p.shortWidthCoefficientMin<p.shortWidthCoefficientMax && ...
       p.shortWidthCoefficientMax<1, ...
    'CycloidalDrive:InvalidShortWidthRange', ...
    'Short-width coefficient limits must satisfy 0 < min < max < 1.');
assert(all(mod(p.Zr_set,1)==0 & p.Zr_set>=3), ...
    'CycloidalDrive:InvalidZrSet','Zr_set must contain integers >= 3.');
assert(all(mod(p.nOut_set,1)==0 & p.nOut_set>=1), ...
    'CycloidalDrive:InvalidNOutSet','nOut_set must contain positive integers.');
assert(p.clear_min<=p.clear_max && p.outClear_min<=p.outClear_max && ...
       p.e_min<=p.e_max && p.Rp_min<=p.Rp_max && ...
       p.dRing_min<=p.dRing_max && p.dOut_min<=p.dOut_max && ...
       p.tDisc_min<=p.tDisc_max && p.rHole_min<=p.rHole_max, ...
    'CycloidalDrive:InvalidBounds','One or more bounds are reversed.');
assert(numel(p.rankWeights)==4 && all(p.rankWeights>=0) && sum(p.rankWeights)>0, ...
    'CycloidalDrive:InvalidWeights', ...
    'rankWeights must contain four nonnegative values with positive sum.');
end
